export const items = [
    { name: "Milk", categoryName: "Dairy" },
    { name: "Cheese", categoryName: "Dairy" },
    { name: "Yogurt", categoryName: "Dairy" },
    { name: "Butter", categoryName: "Dairy" },
    { name: "Eggs", categoryName: "Dairy" },
    { name: "Cream", categoryName: "Dairy" },
    { name: "Sour Cream", categoryName: "Dairy" },
    { name: "Ice Cream", categoryName: "Dairy" },
    { name: "Cottage Cheese", categoryName: "Dairy" },
    { name: "Buttermilk", categoryName: "Dairy" },

    { name: "Bread", categoryName: "Bakery" },
    { name: "Baguette Magique", categoryName: "Bakery" },
    { name: "Croissant", categoryName: "Bakery" },
    { name: "Bagels", categoryName: "Bakery" },
    { name: "Rolls", categoryName: "Bakery" },
    { name: "Donuts", categoryName: "Bakery" },
    { name: "Muffins", categoryName: "Bakery" },
    { name: "Scones", categoryName: "Bakery" },
    { name: "Pita Bread", categoryName: "Bakery" },
    { name: "Tortillas", categoryName: "Bakery" },

    { name: "Apples", categoryName: "Fruits" },
    { name: "Bananas", categoryName: "Fruits" },
    { name: "Oranges", categoryName: "Fruits" },
    { name: "Strawberries", categoryName: "Fruits" },
    { name: "Grapes", categoryName: "Fruits" },
    { name: "Blueberries", categoryName: "Fruits" },
    { name: "Mango", categoryName: "Fruits" },
    { name: "Pineapple", categoryName: "Fruits" },
    { name: "Cherries", categoryName: "Fruits" },
    { name: "Peaches", categoryName: "Fruits" },

    { name: "Lettuce", categoryName: "Vegetables" },
    { name: "Spinach", categoryName: "Vegetables" },
    { name: "Kale", categoryName: "Vegetables" },
    { name: "Broccoli", categoryName: "Vegetables" },
    { name: "Cauliflower", categoryName: "Vegetables" },
    { name: "Carrots", categoryName: "Vegetables" },
    { name: "Celery", categoryName: "Vegetables" },
    { name: "Bell Peppers", categoryName: "Vegetables" },
    { name: "Tomatoes", categoryName: "Vegetables" },
    { name: "Cucumber", categoryName: "Vegetables" },

    { name: "Chicken Breast", categoryName: "Meat" },
    { name: "Ground Beef", categoryName: "Meat" },
    { name: "Pork Chops", categoryName: "Meat" },
    { name: "Bacon", categoryName: "Meat" },
    { name: "Sausages", categoryName: "Meat" },
    { name: "Turkey", categoryName: "Meat" },
    { name: "Ham", categoryName: "Meat" },
    { name: "Lamb Chops", categoryName: "Meat" },
    { name: "Steak", categoryName: "Meat" },
    { name: "Salami", categoryName: "Meat" },

    { name: "Salmon", categoryName: "Seafood" },
    { name: "Shrimp", categoryName: "Seafood" },
    { name: "Crab", categoryName: "Seafood" },
    { name: "Lobster", categoryName: "Seafood" },
    { name: "Tuna", categoryName: "Seafood" },
    { name: "Cod", categoryName: "Seafood" },
    { name: "Scallops", categoryName: "Seafood" },
    { name: "Clams", categoryName: "Seafood" },
    { name: "Oysters", categoryName: "Seafood" },
    { name: "Trout", categoryName: "Seafood" },

    { name: "Rice", categoryName: "Grains" },
    { name: "Quinoa", categoryName: "Grains" },
    { name: "Oats", categoryName: "Grains" },
    { name: "Pasta", categoryName: "Grains" },
    { name: "Couscous", categoryName: "Grains" },
    { name: "Flour", categoryName: "Grains" },
    { name: "Bread Crumbs", categoryName: "Grains" },
    { name: "Barley", categoryName: "Grains" },
    { name: "Millet", categoryName: "Grains" },
    { name: "Cornmeal", categoryName: "Grains" },

    { name: "Olive Oil", categoryName: "Condiments" },
    { name: "Vinegar", categoryName: "Condiments" },
    { name: "Ketchup", categoryName: "Condiments" },
    { name: "Mayonnaise", categoryName: "Condiments" },
    { name: "Mustard", categoryName: "Condiments" },
    { name: "Soy Sauce", categoryName: "Condiments" },
    { name: "Hot Sauce", categoryName: "Condiments" },
    { name: "Honey", categoryName: "Condiments" },
    { name: "Peanut Butter", categoryName: "Condiments" },
    { name: "Jam", categoryName: "Condiments" },

    { name: "Salt", categoryName: "Spices" },
    { name: "Pepper", categoryName: "Spices" },
    { name: "Paprika", categoryName: "Spices" },
    { name: "Cumin", categoryName: "Spices" },
    { name: "Oregano", categoryName: "Spices" },
    { name: "Basil", categoryName: "Spices" },
    { name: "Chili Powder", categoryName: "Spices" },
    { name: "Cinnamon", categoryName: "Spices" },
    { name: "Garlic Powder", categoryName: "Spices" },
    { name: "Thyme", categoryName: "Spices" },

    { name: "Toilet Paper", categoryName: "Household" },
    { name: "Paper Towels", categoryName: "Household" },
    { name: "Dish Soap", categoryName: "Household" },
    { name: "Laundry Detergent", categoryName: "Household" },
    { name: "Trash Bags", categoryName: "Household" },
    { name: "Sponges", categoryName: "Household" },
    { name: "Aluminum Foil", categoryName: "Household" },
    { name: "Plastic Wrap", categoryName: "Household" },
    { name: "Napkins", categoryName: "Household" },
    { name: "Cleaning Spray", categoryName: "Household" },
];
